server.port: 56082
spring.application.name: reliable-message-bank2
server.servlet.context-path: /bank2

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank2?useUnicode=true
    username: root
    password: 1q1w1e1r

rocketmq:
  name-server: 10.13.3.13:9876
  producer.group: producer_bank2

logging:
  level:
    root: info
    org.springframework.web: info
    com.topsail: debug